"""Focused checker tests: source only until separately admitted.

Run only in a separately reviewed read-only guest with the reviewed checker
mounted at /trusted/check_l1.py and pinned fixtures at /candidate/examples/l0.
This suite imports that trusted copy, never a candidate host module. All
process launches and writes in tested orchestration paths are mocked; these
tests do not establish actual isolation, cgroup enforcement or runtime proof.
Generator tests and the fixed 41-case acceptance remain separate evidence.
"""
import copy
import importlib.util
from pathlib import Path
import sys
import unittest
from unittest.mock import MagicMock, call, patch

spec = importlib.util.spec_from_file_location('reviewed_check_l1', '/trusted/check_l1.py')
if spec is None or spec.loader is None:
    raise RuntimeError('reviewed checker is required in the admitted guest')
C = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = C
spec.loader.exec_module(C)


def fixtures():
    root = Path('/candidate/examples/l0')
    return {name: (root / name).read_bytes() for name in (
        'tag_list.json', 'tag_unique_sorted.patch', 'composed.json', 'composed_inputs.json')}


def success(value=1, kind='int'):
    return {'schema': C.SCHEMA, 'ok': True, 'command': 'run',
            'program_digest': 'sha256:'+'1'*64, 'result_type': kind, 'result': value}


def refused(message='invalid input'):
    return {'schema': C.SCHEMA, 'ok': False, 'command': 'run',
            'error': {'code': 'value.type', 'message': message}}


def full_report():
    return {'cases_selected': 41, 'cases_run': 41, 'failures': [], 'skips': [],
            'cases': [{'case': name, 'status': 'MATCH', 'observations': [{'phase': 'test'}]}
                      for name in C.CASE_IDS]}


class Rejections(unittest.TestCase):
    def rejects(self, code, action):
        with self.assertRaises(C.Failure) as caught:
            action()
        self.assertEqual(caught.exception.code, code)

    def test_json_duplicate_keys_and_non_json_values(self):
        for raw in (b'{"a":0,"a":1}', b'{"a":{"b":0,"b":1}}'):
            self.rejects('output.duplicate_key', lambda raw=raw: C.decode(raw))
        self.rejects('output.constant', lambda: C.decode(b'{"a":NaN}'))
        for raw in (b'{}{}', b'\xff', b'{'):
            self.rejects('output.json', lambda raw=raw: C.decode(raw))

    def test_deep_types_are_not_python_numeric_equality(self):
        self.assertFalse(C.same({'a': [True]}, {'a': [1]}))
        self.assertFalse(C.same([1], [1.0]))
        self.assertFalse(C.same([], ()))
        self.assertTrue(C.same({'a': [1, False]}, {'a': [1, False]}))
        self.rejects('output.value_type', lambda: C.envelope(0, success(True)))

    def test_exact_envelopes_and_exit_codes(self):
        self.assertEqual(C.envelope(0, success()), success())
        self.assertEqual(C.envelope(2, refused()), refused())
        self.rejects('output.exit', lambda: C.envelope(2, success()))
        self.rejects('output.exit', lambda: C.envelope(0, refused()))
        self.rejects('output.shape', lambda: C.envelope(0, {**success(), 'extra': 1}))
        partial = success()
        del partial['result']
        self.rejects('output.shape', lambda: C.envelope(0, partial))
        self.rejects('output.envelope', lambda: C.envelope(0, {**success(), 'ok': 1}))
        self.rejects('output.envelope', lambda: C.envelope(0, {**success(), 'command': 'check'}))
        self.rejects('output.envelope', lambda: C.envelope(0, {**success(), 'schema': 'wrong'}))

    def test_error_messages_are_path_free(self):
        for message in ('/private/file', 'C:\\private', 'relative/file', '~/file', 'bad\nline', ''):
            self.rejects('output.error_message', lambda message=message: C.envelope(2, refused(message)))
        C.compare(C.envelope(2, refused('invalid value')), C.envelope(2, refused('wrong type')))

    def test_mismatched_observations(self):
        self.rejects('equivalence.value', lambda: C.compare(success(), success(2)))
        self.rejects('equivalence.outcome', lambda: C.compare(success(), refused()))
        other = refused()
        other['error']['code'] = 'limit.list'
        self.rejects('equivalence.error', lambda: C.compare(refused(), other))

    def test_binding_tamper_revision_generator_and_embedded_digest(self):
        selected = 'sha256:'+'1'*64
        data = C.encoded([selected, 'int']).hex().encode('ascii')
        source = (b'# Generated by bagaev/l1-cpython/v1; fixed L0 program.\n'
                  b'_DATA = json.loads(bytes.fromhex("'+data+b'").decode("ascii"))\n')
        identity = {'program_digest': selected, 'generator_revision': C.REVISION,
                    'artifact_sha256': C.sha(source)}
        C.bind(source, identity, selected)
        self.rejects('binding.hash', lambda: C.bind(source+b'\n', identity, selected))
        self.rejects('binding.revision', lambda: C.bind(source, identity, 'sha256:'+'2'*64))
        self.rejects('binding.generator', lambda: C.bind(source, {**identity, 'generator_revision': 'other'}, selected))
        changed = source.replace(data, C.encoded(['sha256:'+'2'*64, 'int']).hex().encode())
        self.rejects('binding.embedded', lambda: C.bind(changed, {**identity, 'artifact_sha256': C.sha(changed)}, selected))
        duplicate = source+source.splitlines(keepends=True)[1]
        self.rejects('binding.embedded', lambda: C.bind(duplicate, {**identity, 'artifact_sha256': C.sha(duplicate)}, selected))

    def test_zero_missing_skipped_duplicate_and_partial_cases(self):
        C.complete(full_report())
        for field, value, code in (
            ('cases_selected', 0, 'cases.selected'), ('cases_selected', True, 'cases.selected'),
            ('cases_run', 0, 'cases.run'), ('cases_run', 40, 'cases.run'),
            ('failures', [{'code': 'bad'}], 'cases.failures'), ('skips', ['L1-01'], 'cases.failures'),
            ('cases', [], 'cases.records'), ('cases', None, 'cases.records'),
        ):
            report = full_report()
            report[field] = value
            self.rejects(code, lambda report=report: C.complete(report))
        for mutate in (
            lambda r: r['cases'][1].update(case=r['cases'][0]['case']),
            lambda r: r['cases'][1].update(status='SKIP'),
            lambda r: r['cases'][1].update(observations=[]),
        ):
            report = full_report()
            mutate(report)
            self.rejects('cases.match', lambda: C.complete(report))

    def test_supplemental_zero_hidden_skips_malformed_and_mismatch(self):
        good = {'selected': 5, 'run': 5, 'failures': 0, 'errors': 0,
                'skipped': 0, 'expected_failures': 0, 'unexpected_successes': 0}
        self.assertFalse(C.supplemental(0, good)['authoritative'])
        for field, value in (('selected', 0), ('run', 4), ('skipped', 1),
                             ('expected_failures', 1), ('unexpected_successes', 1), ('errors', 1)):
            self.rejects('tests.incomplete', lambda field=field, value=value:
                         C.supplemental(0, {**good, field: value}))
        self.rejects('tests.incomplete', lambda: C.supplemental(2, good))
        self.rejects('tests.counts', lambda: C.supplemental(0, {**good, 'run': True}))
        self.rejects('tests.shape', lambda: C.supplemental(0, {}))
        failed = {**good, 'failures': 1, 'skipped': 2}
        self.assertEqual(C.test_counts(1, failed),
                         {'authoritative': False, 'terminal_exit': 1, **failed})

    def test_guest_rejects_bad_frames_without_launching(self):
        guard = {'guard': {'memory.max': str(C.MEMORY), 'memory.swap.max': '0',
                          'pids.max': '16', 'cpu.max': '50000 100000'}}
        runtime = {'runtime': {'implementation': 'CPython', 'version': '3.14.4',
                   'executable': '/usr/bin/python3', 'architecture': 'x86_64',
                   'seccomp': 2, 'no_new_privs': 1}}
        raw = b'\n'.join(map(C.encoded, (guard, runtime, success())))+b'\n'
        cases = ((raw, b'', None), (raw+b'{}\n', b'', 'output.framing'),
                 (raw[:-1], b'', 'output.framing'), (b'', b'', 'sandbox.start'),
                 (raw, b'unexpected', 'output.stderr'),
                 (raw.replace(b'3.14.4', b'3.13.9'), b'', 'sandbox.runtime'),
                 (raw.replace(b'50000 100000', b'100000 100000'), b'', 'sandbox.limits'))
        for output, stderr, wanted in cases:
            guest = C.Guest(Path('/root'), MagicMock(), {}, float('inf'))
            with patch.object(C, 'put'), patch.object(C, 'capture', return_value=(0, output, stderr)), \
                 patch.object(guest, 'cleanup'), patch.object(guest, 'tool', side_effect=lambda name: name):
                if wanted:
                    self.rejects(wanted, lambda: guest.run({'mode': 'probe'}))
                else:
                    self.assertEqual(guest.run({'mode': 'probe'}), (0, success()))

    def test_no_candidate_runs_before_probe(self):
        guest = C.Guest(Path('/root'), Path('/jobs'), {}, float('inf'))
        self.rejects('sandbox.unprobed', lambda: guest.run({'mode': 'artifact'}))

    def test_success_requires_completed_scratch_cleanup(self):
        counts = {'selected': 1, 'run': 1, 'failures': 0, 'errors': 0,
                  'skipped': 0, 'expected_failures': 0, 'unexpected_successes': 0}
        manifest = {'checker_sha256': '1'*64, 'generator_revision': C.REVISION,
                    'files': {}, 'runtime': {}, 'tools': {}}
        for cleanup_error in (None, OSError('cleanup refused')):
            with self.subTest(cleanup_failed=cleanup_error is not None):
                temporary = MagicMock()
                temporary.__enter__.return_value = '/synthetic-scratch'
                temporary.__exit__.return_value = False
                temporary.__exit__.side_effect = cleanup_error
                guest = MagicMock(runtime={}, handles=[])
                guest.run.return_value = (0, counts)
                acceptance = MagicMock(records=full_report()['cases'], failures=[])
                # No directory creation, file reads, subprocesses or guests.
                with patch.object(C.Path, 'resolve', lambda path, **_kwargs: path), \
                     patch.object(C.Path, 'is_dir', return_value=True), \
                     patch.object(C.Path, 'mkdir'), \
                     patch.object(C.tempfile, 'TemporaryDirectory', return_value=temporary), \
                     patch.object(C, 'stage', return_value=manifest), \
                     patch.object(C, 'read_file', return_value=b'{}'), \
                     patch.object(C, 'Guest', return_value=guest), \
                     patch.object(C, 'Acceptance', return_value=acceptance), \
                     patch.object(C.subprocess, 'Popen', side_effect=AssertionError('unexpected process')):
                    report = C.check(Path('/synthetic-snapshot'), Path('/admission.json'), '2'*64)
                acceptance.all.assert_called_once_with()
                self.assertEqual(guest.run.call_args_list,
                                 [call({'mode': 'checker-tests'}), call({'mode': 'tests'})])
                temporary.__exit__.assert_called_once_with(None, None, None)
                self.assertEqual(report['cases_run'], 41)
                self.assertEqual(report['owned_handles'], [])
                for name in ('checker_tests', 'supplemental_generator_tests'):
                    self.assertEqual(report[name]['run'], 1)
                if cleanup_error is None:
                    self.assertIs(report['ok'], True)
                    self.assertEqual(report['status'], 'PASS')
                    self.assertEqual(report['terminal_exit'], 0)
                else:
                    self.assertIs(report['ok'], False)
                    self.assertEqual(report['status'], 'BLOCKED')
                    self.assertNotEqual(report['terminal_exit'], 0)
                    self.assertEqual(report['error'], {'code': 'environment.operation'})

    def test_gate_rejects_artifact_on_refusal(self):
        guest = MagicMock()
        guest.run.return_value = (2, {'ok': False, 'error': {'code': 'node.duplicate', 'message': 'duplicate node'},
                                     'emitted': True, 'original_unchanged': True})
        runner = C.Acceptance(guest, fixtures())
        self.rejects('generation.refusal', lambda: runner.generate(b'{}', expected_error='node.duplicate'))

    def test_file_gate_rejects_special_files_before_read_and_closes(self):
        path = Path('/candidate/source.py')
        for mode, size in ((C.stat.S_IFIFO, 0), (C.stat.S_IFDIR, 0),
                           (C.stat.S_IFCHR, 0), (C.stat.S_IFSOCK, 0),
                           (C.stat.S_IFREG, 5)):
            with self.subTest(mode=mode, size=size), \
                 patch.object(C.os, 'open', return_value=37) as opened, \
                 patch.object(C.os, 'fstat', return_value=MagicMock(st_mode=mode, st_size=size)) as inspected, \
                 patch.object(C.os, 'read') as read, patch.object(C.os, 'close') as closed:
                with self.assertRaises(C.Failure) as caught:
                    C.read_file(path, maximum=4)
                self.assertEqual(caught.exception.code, 'input.file')
                self.assertTrue(caught.exception.blocked)
                opened.assert_called_once_with(path, C.os.O_RDONLY | C.os.O_NONBLOCK
                                               | C.os.O_CLOEXEC | C.os.O_NOFOLLOW)
                inspected.assert_called_once_with(37)
                read.assert_not_called()
                closed.assert_called_once_with(37)

    def test_file_read_uses_bounded_same_descriptor_and_closes(self):
        with patch.object(C.os, 'open', return_value=37), \
             patch.object(C.os, 'fstat', return_value=MagicMock(st_mode=C.stat.S_IFREG, st_size=3)), \
             patch.object(C.os, 'read', side_effect=[b'a', b'bc', b'']) as read, \
             patch.object(C.os, 'close') as closed:
            self.assertEqual(C.read_file(Path('/candidate/source.py'), maximum=3), b'abc')
            self.assertEqual(read.call_args_list, [call(37, 4), call(37, 3), call(37, 1)])
            closed.assert_called_once_with(37)
        # A file growing after fstat still cannot escape the read bound.
        with patch.object(C.os, 'open', return_value=37), \
             patch.object(C.os, 'fstat', return_value=MagicMock(st_mode=C.stat.S_IFREG, st_size=3)), \
             patch.object(C.os, 'read', return_value=b'abcd') as read, \
             patch.object(C.os, 'close') as closed:
            self.rejects('input.size', lambda: C.read_file(Path('/candidate/source.py'), maximum=3))
            read.assert_called_once_with(37, 4)
            closed.assert_called_once_with(37)

    def test_file_descriptor_cleanup_on_open_stat_and_read_errors(self):
        with patch.object(C.os, 'open', side_effect=OSError('open refused')), \
             patch.object(C.os, 'close') as closed:
            with self.assertRaises(OSError):
                C.read_file(Path('/candidate/source.py'))
            closed.assert_not_called()
        for failure in ('fstat', 'read'):
            with self.subTest(failure=failure), \
                 patch.object(C.os, 'open', return_value=37), \
                 patch.object(C.os, 'fstat', return_value=MagicMock(st_mode=C.stat.S_IFREG, st_size=0)), \
                 patch.object(C.os, 'read', return_value=b''), \
                 patch.object(C.os, failure, side_effect=OSError('descriptor operation refused')), \
                 patch.object(C.os, 'close') as closed:
                with self.assertRaises(OSError):
                    C.read_file(Path('/candidate/source.py'))
                closed.assert_called_once_with(37)


class FixtureCapture(C.Acceptance):
    """Inspect the fixed recipes without generator, oracle or artifact execution."""
    def __init__(self):
        super().__init__(None, fixtures())
        self.selected = []
        self.actions = {}

    def record(self, name, action):
        self.selected.append(name)
        self.name = name
        self.actions[name] = []
        action()

    def run(self, selected, inputs, expected=None, error=None):
        self.actions[self.name].append((selected, inputs, expected, error))

    def gate(self, raw, code, patch=None):
        self.actions[self.name].append((raw, code, patch))

    def patch_atomic(self):
        self.actions[self.name].append(('patch',))

    def equality(self, reordered=False):
        self.actions[self.name].append(('equality', reordered))

    def tamper(self, revision=False):
        self.actions[self.name].append(('tamper', revision))


class FrozenRecipes(unittest.TestCase):
    def test_whole_profile_and_boundary_bytes(self):
        fixed = FixtureCapture()
        fixed.all()
        self.assertEqual(tuple(fixed.selected), C.CASE_IDS)
        self.assertEqual(len(fixed.selected), 41)
        cases = fixed.actions
        for name in ('list-preserves', 'empty', 'duplicates', 'reversed', 'distinct'):
            self.assertEqual(len(cases[name]), 2)
            self.assertEqual(cases[name][0][0], fixed.tag)
            self.assertEqual(cases[name][1][0], fixed.patched)
        self.assertEqual(cases['list-preserves'][0][2], ['red', 'blue', 'red'])
        self.assertEqual(cases['list-preserves'][1][2], ['blue', 'red'])
        self.assertEqual(cases['L1-09'][0][1], b'{}'+b' '*1048574)
        self.assertEqual(cases['L1-19'][0][1], b'{}'+b' '*1048575)
        self.assertEqual(cases['L1-18'][0][1], b'{"x":"'+('é'*2049).encode()+b'"}')
        self.assertIs(cases['L1-01'][0][2], False)
        self.assertIs(cases['L1-02'][0][2], True)
        self.assertEqual(cases['L1-03'][0][2], -(2**63))
        self.assertEqual(cases['L1-04'][0][2], 2**63-1)
        self.assertEqual(len(cases['L1-08'][0][0]['nodes']), 256)
        self.assertEqual(cases['L1-08'][0][0]['result'], {'ref': 'n255'})
        self.assertEqual(len(cases['L1-07'][0][0]['nodes'][1]['items']), 32)
        self.assertEqual(cases['L1-21'][0][1], C.encoded({'a': ['a']*256, 'b': ['a']*256}))
        self.assertEqual(cases['L1-21'][0][3], 'limit.list')
        self.assertEqual(cases['duplicate-key'][0][1], b'{"tags":[],"tags":[]}')
        self.assertEqual(cases['large-integer'][0][1], b'{"tags":'+b'9'*5000+b'}')
        self.assertEqual(cases['L1-14'], [('equality', False)])
        self.assertEqual(cases['L1-20'], [('equality', True)])
        self.assertEqual(cases['L1-15'], [('tamper', False)])
        self.assertEqual(cases['L1-16'], [('tamper', True)])

    def test_frozen_oracle_and_fixture_hashes(self):
        self.assertEqual(C.FROZEN['src/bagaev_l0.py'],
                         'e74aa0cef4ba84d5f17865194868901b36dce12299c81189b2172fa08c6eb922')
        for name, raw in fixtures().items():
            self.assertEqual(C.sha(raw), C.FROZEN['examples/l0/'+name])


if __name__ == '__main__':
    unittest.main()
